Repository esp8266/Arduino, pull requests merged in 2018-03, with the labels that each got.

#4401 Reference to a arrow/_right that after doesn't exist
  doc/faq/readme.rst
Labels: component: documentation

#3798 Bugfix/persistentchecks
  libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp
  libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
  libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
Labels: component: libraries, component: network, type: bug

#3769 Compressed dns
  .gitignore
  libraries/ESP8266WiFi/src/include/UdpContext.h
  libraries/ESP8266mDNS/ESP8266mDNS.cpp
Labels: help wanted
