Repository esp8266/Arduino, pull requests merged in 2019-10, with the labels that each got.

#6608 Minor cleanups in ESPClass
  cores/esp8266/Esp.cpp
Labels: component: core, type: code cleanup

#6624 Update README.md
  README.md
Labels: component: documentation

#6326 Reduce the IRAM usage of I2C code by 600-1500 bytes
  cores/esp8266/core_esp8266_si2c.cpp
  cores/esp8266/twi.h
  libraries/Wire/Wire.cpp
  libraries/Wire/Wire.h
  tests/restyle.sh
Labels: waiting for feedback

#6485 Wakeup delayed scheduling
  cores/esp8266/Schedule.cpp
  cores/esp8266/Schedule.h
Labels: component: core, type: enhancement

#6438 Update core with upstream umm_malloc
  cores/esp8266/core_esp8266_postmortem.cpp
  cores/esp8266/heap.cpp
  cores/esp8266/umm_malloc/Notes.h
  cores/esp8266/umm_malloc/README.md
  cores/esp8266/umm_malloc/dbglog/LICENSE
  cores/esp8266/umm_malloc/dbglog/README.txt
  cores/esp8266/umm_malloc/dbglog/dbglog.h
  cores/esp8266/umm_malloc/umm_info.c
  cores/esp8266/umm_malloc/umm_integrity.c
  cores/esp8266/umm_malloc/umm_local.c
  cores/esp8266/umm_malloc/umm_local.h
  cores/esp8266/umm_malloc/umm_malloc.cpp
  cores/esp8266/umm_malloc/umm_malloc.h
  cores/esp8266/umm_malloc/umm_malloc_cfg.h
  cores/esp8266/umm_malloc/umm_performance.cpp
  cores/esp8266/umm_malloc/umm_performance.h
  cores/esp8266/umm_malloc/umm_poison.c
  cores/esp8266/umm_malloc/umm_stats.h
Labels: type: enhancement

#6580 Spi slave improvments
  libraries/SPISlave/src/SPISlave.cpp
  libraries/SPISlave/src/SPISlave.h
  libraries/SPISlave/src/hspi_slave.c
Labels: type: code cleanup, type: enhancement

#6571 Further const correctness / String by reference passing cleanups
  libraries/ArduinoOTA/ArduinoOTA.cpp
  libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
  libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h
  libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h
  libraries/ESP8266WebServer/src/ESP8266WebServer.h
  libraries/ESP8266WiFiMesh/src/ESP8266WiFiMesh.cpp
  libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
  libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h
  libraries/ESP8266mDNS/src/ESP8266mDNS_Legacy.cpp
  libraries/ESP8266mDNS/src/LEAmDNS.cpp
  libraries/ESP8266mDNS/src/LEAmDNS.h
Labels: type: code cleanup

#4107 added public cleanAPlist() function
  libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp
  libraries/ESP8266WiFi/src/ESP8266WiFiMulti.h
Labels: component: libraries, type: enhancement

#6607 Cleanup base64::encode functions
  cores/esp8266/base64.cpp
  cores/esp8266/base64.h
  cores/esp8266/libb64/cencode.cpp
  libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
Labels: component: core, type: enhancement
