Repository esp8266/Arduino, pull requests merged in 2020-08, with the labels that each got.

#7521 Fix and add details to Serial doc
  doc/reference.rst
Labels: component: documentation

#7356 avoid circular #include dependence for PolledTimeout
  cores/esp8266/Arduino.h
  cores/esp8266/Esp.h
  cores/esp8266/PolledTimeout.h
  cores/esp8266/core_esp8266_features.h
  tests/host/common/MockEsp.cpp
  tests/host/common/mock.h
Labels: alpha

#7531 doc: gcc handles duplicate literal strings
  doc/reference.rst
Labels: component: documentation

#7556 Use direct member initialization instead of ctr initialisation
  libraries/ArduinoOTA/ArduinoOTA.cpp
  libraries/ArduinoOTA/ArduinoOTA.h
  libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp
  libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.h
Labels: type: code cleanup
