Repository esp8266/Arduino, pull requests merged in 2020-09, with the labels that each got.

#7557 Fixup #7554: Inline, fewer LOC, remove redundant definition in cpp.
  cores/esp8266/Esp.cpp
  cores/esp8266/Esp.h
Labels: type: bug, type: code cleanup

#7579 Update DigestAuthorization.ino (Simple example update)
  libraries/ESP8266HTTPClient/examples/DigestAuthorization/DigestAuthorization.ino
Labels: component: examples, type: enhancement

#7581 Fix message typo
  libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp
Labels: type: code cleanup

#7560 Avoid #includes with a surrounding namespace
  libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h
  libraries/ESP8266WebServer/src/ESP8266WebServer.h
  libraries/ESP8266WebServer/src/Parsing-impl.h
  libraries/ESP8266WebServer/src/detail/RequestHandler.h
  libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h
Labels: type: code cleanup
