Repository esp8266/Arduino, pull requests merged in 2020-10, with the labels that each got.

#7624 Pull deprecated axtls link
  README.md
Labels: component: documentation

#7514 New flash writing method with offset/memory/size alignment handling
  cores/esp8266/Esp.cpp
  cores/esp8266/Esp.h
  cores/esp8266/Updater.cpp
  cores/esp8266/flash_hal.cpp
  tests/device/test_spi_flash/test_spi_flash.ino
  tests/host/common/MockEsp.cpp
  tools/sdk/include/spi_flash_geometry.h
Labels: component: core, hacktoberfest-accepted, type: bug

#7652 BREAKING: Add Wrong Password wifi status case
  doc/esp8266wifi/readme.rst
  doc/esp8266wifi/station-class.rst
  libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
  libraries/ESP8266WiFi/src/ESP8266WiFiMulti.cpp
  libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
  libraries/ESP8266WiFi/src/include/wl_definitions.h
  libraries/esp8266/examples/interactive/interactive.ino
Labels: component: libraries, hacktoberfest-accepted, type: enhancement

#7636 MDNS MultiInterface
  libraries/ESP8266mDNS/src/LEAmDNS.cpp
  libraries/ESP8266mDNS/src/LEAmDNS.h
  libraries/ESP8266mDNS/src/LEAmDNS_Control.cpp
  libraries/ESP8266mDNS/src/LEAmDNS_Helpers.cpp
  libraries/ESP8266mDNS/src/LEAmDNS_Structs.cpp
  libraries/ESP8266mDNS/src/LEAmDNS_Transfer.cpp
  tests/host/Makefile
  tests/host/common/mock.h
Labels: hacktoberfest-accepted

#7653 Add Copyright notice to Schedule.h
  cores/esp8266/Schedule.cpp
  cores/esp8266/Schedule.h
Labels: hacktoberfest-accepted, type: code cleanup

#7657 BREAKING: Change return type of RSSI()
  libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp
  libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h
Labels: component: libraries, hacktoberfest-accepted, type: enhancement

#7656 BREAKING: Change return type of channel()
  libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
  libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h
Labels: component: libraries, hacktoberfest-accepted, type: enhancement

#7630 BREAKING: Change return EEPROM.end() to bool
  libraries/EEPROM/EEPROM.cpp
  libraries/EEPROM/EEPROM.h
Labels: component: libraries, hacktoberfest-accepted, type: enhancement

#7659 Fix Netdump library architecture
  libraries/Netdump/library.properties
Labels: component: libraries, hacktoberfest-accepted

#7666 Fix eboot crash with exception 28. ets_printf() should take pointer argument.
  bootloaders/eboot/eboot.c
  bootloaders/eboot/eboot.elf
Labels: hacktoberfest-accepted

#7670 boards.txt: sort by displayed name
  boards.txt
  doc/boards.rst
  package/package_esp8266com_index.template.json
  tools/boards.txt.py
Labels: hacktoberfest-accepted

#7674 Remove Travis-CI configuration
  .travis.yml
Labels: hacktoberfest-accepted

#7676 Fix long password validation in WebServer
  libraries/ESP8266WebServer/src/ESP8266WebServer-impl.h
Labels: component: web, hacktoberfest-accepted, type: bug

#7655 Refactor WiFi scan example
  libraries/ESP8266WiFi/examples/WiFiScan/WiFiScan.ino
Labels: component: examples, hacktoberfest-accepted

#7658 BREAKING: Add Print::availableForWrite method
  cores/esp8266/FS.cpp
  cores/esp8266/FS.h
  cores/esp8266/FSImpl.h
  cores/esp8266/HardwareSerial.h
  cores/esp8266/Print.h
  libraries/ESP8266WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino
  libraries/ESP8266WiFi/src/WiFiClient.cpp
  libraries/ESP8266WiFi/src/WiFiClient.h
  libraries/Netdump/src/Netdump.cpp
  libraries/SDFS/src/SDFS.h
Labels: component: core, hacktoberfest-accepted, type: enhancement

#7679 Revive a dead link
  doc/esp8266wifi/server-examples.rst
Labels: hacktoberfest-accepted

#7681 Catch and display SSL errors for fatal alerts
  libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp
Labels: hacktoberfest-accepted

#7675 Add Stream loaders for BearSSL
  libraries/ESP8266WiFi/src/BearSSLHelpers.cpp
  libraries/ESP8266WiFi/src/BearSSLHelpers.h
Labels: component: TLS, hacktoberfest-accepted, type: enhancement

#7685 compile failure fix with FS_NO_GLOBALS flag
  libraries/ESP8266WiFi/src/CertStoreBearSSL.cpp
Labels: hacktoberfest-accepted

#7686 Hook up custom timestamp proc for SD/SDFS
  libraries/SDFS/src/SDFS.cpp
  libraries/SDFS/src/SDFS.h
  tests/host/fs/test_fs.cpp
Labels: hacktoberfest-accepted, type: enhancement
