Repository esp8266/Arduino, pull requests merged in 2020-05, with the labels that each got.

#6476 bugfix2/ESP8266HTTPClient
  libraries/ESP8266HTTPClient/examples/ReuseConnectionV2/ReuseConnectionV2.ino
  libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp
Labels: type: bug

#7291 Allocate BSSL stack for SigningVerifier
  libraries/ESP8266WiFi/src/BearSSLHelpers.h
Labels: type: bug

#7310 CryptoFix
  cores/esp8266/Crypto.cpp
  cores/esp8266/Crypto.h
Labels: type: bug

#7275 Allow non-aligned PSTR()
  cores/esp8266/umm_malloc/umm_local.h
  tools/sdk/libc/xtensa-lx106-elf/include/sys/pgmspace.h
Labels: component: core, type: enhancement

#7312 Flash size reduction for mime-type
  libraries/ESP8266WebServer/src/detail/mimetable.cpp
  libraries/ESP8266WebServer/src/detail/mimetable.h
Labels: component: libraries, type: enhancement

#7338 Add documentation on recovering from deep sleep with WAKE_RF_DISABLED
  doc/faq/readme.rst
  doc/libraries.rst
Labels: component: documentation, type: enhancement

#7324 Return FALSE on seek past EOF
  libraries/LittleFS/src/LittleFS.h
  tests/host/fs/test_fs.inc
Labels: type: bug
