Repository esp8266/Arduino, pull requests merged in 2021-04, with the labels that each got.

#7951 fix WiFiClient::write(from flash or iram)
  libraries/ESP8266WiFi/src/WiFiClient.cpp
  libraries/ESP8266WiFi/src/include/ClientContext.h
Labels: alpha

#7953 Sanitizing HW serial's uart.cpp just a little more.
  cores/esp8266/uart.cpp
Labels: component: core, type: bug

#6117 Improve timeout in Updater.
  cores/esp8266/Updater.cpp
  cores/esp8266/Updater.h
Labels: waiting for feedback

#7010 Hardware WDT Stack Dump Tool
  boards.txt
  cores/esp8266/core_esp8266_app_entry_noextra4k.cpp
  cores/esp8266/core_esp8266_main.cpp
  cores/esp8266/heap.cpp
  cores/esp8266/hwdt_app_entry.cpp
  cores/esp8266/hwdt_app_entry.h
  cores/esp8266/umm_malloc/umm_local.c
  cores/esp8266/umm_malloc/umm_local.h
  libraries/esp8266/examples/HwdtStackDump/HwdtStackDump.ino
  libraries/esp8266/examples/HwdtStackDump/ProcessKey.ino
  tools/boards.txt.py
Labels: alpha

#7902 [BREAKING] Disable WiFi at boot by default
  cores/esp8266/core_esp8266_features.h
  cores/esp8266/core_esp8266_main.cpp
  cores/esp8266/coredecls.h
  doc/esp8266wifi/generic-class.rst
  doc/esp8266wifi/readme.rst
  doc/faq/a01-espcomm_sync-failed.rst
  doc/faq/a04-board-generic-is-unknown.rst
  doc/faq/readme.rst
  doc/filesystem.rst
  doc/libraries.rst
  doc/mmu.rst
  doc/ota_updates/readme.rst
  libraries/ESP8266WiFi/examples/EarlyDisableWiFi/EarlyDisableWiFi.ino
  libraries/ESP8266WiFi/examples/WiFiShutdown/WiFiShutdown.ino
  libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp
  libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h
  libraries/ESP8266WiFi/src/enable_wifi_at_boot_time.cpp
  libraries/esp8266/examples/SerialStress/SerialStress.ino
  libraries/esp8266/examples/UartDownload/UartDownload.ino
  libraries/lwIP_w5500/examples/TCPClient/TCPClient.ino
  tests/device/test_serial/test_serial.ino
  tests/device/test_spi_flash/test_spi_flash.ino
Labels: alpha

#7978 Resolve "PWM-locked" / "phase-locked" waveform merge leftover in Servo lib
  cores/esp8266/core_esp8266_waveform_pwm.cpp
  libraries/Servo/src/Servo.cpp
Labels: component: libraries, type: bug

#7987 fixes for WiFiClient::write(Stream)
  cores/esp8266/StreamSend.cpp
  libraries/ESP8266WebServer/src/ESP8266WebServer.h
  libraries/ESP8266WiFi/examples/WiFiEcho/WiFiEcho.ino
  libraries/ESP8266WiFi/src/WiFiClient.cpp
  libraries/ESP8266WiFi/src/WiFiClient.h
  libraries/ESP8266WiFi/src/include/ClientContext.h
  tests/host/common/include/ClientContext.h
Labels: alpha
